services:
  node:
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - ~/.pnpm-store:/pnpm-store
    tty: true
    stdin_open: true
volumes:
  app_node_modules:
